booksmith/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "booksmith"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("book-listing-form/", views.BookListingFormView.as_view(), name="book_listing_form"),
    path("book-detail/<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("booksmith.urls")),
    path("accounts/", include("accounts.urls")),

    path("password-change/", auth_views.PasswordChangeView.as_view(), name="password_change"),
    path("password-change/done/", auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path("password-reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("verify-email/<str:uidb64>/<str:token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booksmith/models.py
from django.db import models
from django import forms
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from accounts.models import CustomUser

fs = FileSystemStorage(location=settings.MEDIA_ROOT)

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name="books")
    publisher = models.CharField(max_length=100)
    publication_date = models.DateField()
    description = models.CharField(max_length=1000)
    cover_image = models.ImageField()

    def __str__(self):
        return f"{self.title} ({self.author})"

class Review(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="reviews", null=True)
    review = models.CharField(max_length=1000)
    book = models.ForeignKey(Book, related_name="reviews", on_delete=models.CASCADE)

class Favourite(models.Model):
    user = models.ManyToManyField(CustomUser)
    book = models.ManyToManyField(Book)

class Collection(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="collection")
    book = models.ManyToManyField(Book)

booksmith/forms.py
from django import forms
from .models import Book


class BookListingForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"
        widgets = {
            "publication_date": forms.DateInput(attrs={
                "type": "date",
            }),
            "description": forms.Textarea(attrs={
                "rows": 5,
                "cols": 10,
            }),
        }

booksmith/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, HttpResponse
import requests
from .forms import BookListingForm
from django.views.generic import CreateView,ListView, DetailView, UpdateView, DeleteView
from .models import Book
from django.urls import reverse_lazy

# Create your views here.
def home_view(request):
    response = requests.get("https://openlibrary.org/search.json", params="money")
    data = response.json()

    num_book_to_show = 10

    books = [
        {
            "title": book.get("title", ""),
            "author": book.get("author", []),
            "cover": book.get("cover", "")
        }
        for book in data.get("docs", [])[:num_book_to_show]
    ]
    print(books)

    return render(request, "booksmith/home.html", {"books": books})


class HomeView(ListView):
    model = Book
    template_name = "booksmith/home.html"
    context_object_name = "books"

    def get_queryset(self):
        query = self.request.GET.get("search")
        if query:
            return Book.objects.filter(title__icontains=query)
        else:
            return super().get_queryset()


class BookListingFormView(CreateView):
    model = Book
    form_class = BookListingForm
    template_name = "booksmith/book-listing-form.html"
    success_url = reverse_lazy("booksmith:home")


class BookDetailView(DetailView):
    model = Book
    template_name = "booksmith/book-detail.html"

booksmith/templates/booksmith/book-detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'booksmith/css/book-detail.css' %}">

<div class="d-flex justify-content-center">
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-4">
                <div class="image-container">
                    <img src="{{ book.cover_image.url }}" class="img-fluid rounded-start rounded-end"
                        alt="{{ book.title }}">
                </div>
            </div>
            <div class="col-md-8 d-flex flex-column">
                <div class="card-body">
                    <h5 class="card-title"> Title: {{ book.title }} <small> ({{ book.genre }})</small></h5>
                    <p class="card-text">
                    <p><h5> Description:</h5> {{ book.description }}</p>
                    <p><b> Author:</b> {{ book.author }}</p>
                    <p><b> Publisher:</b> {{ book.publisher }}</p>
                    <p><b> Publication date:</b> {{ book.publication_date }}</p>
                </div>
                <div class="mt-auto">
                    <a href="{% url 'booksmith:home' %}" class="btn btn-secondary">Go back</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

booksmith/templates/booksmith/book-listing-form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'booksmith/css/book-listing-form.css' %}">

<div class="book-listing-form">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="btn btn-primary">
        <br><br>
        <h4> Want to go back home?</h4>
        <a href="{% url 'booksmith:home' %}" class="btn btn-secondary"> Go back</a>
    </form>
</div>
{% endblock %}

booksmith/templates/booksmith/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Home</title>
{% endblock %}
{% block content%}
<link rel="stylesheet" href="{% static 'booksmith/css/home.css' %}">
<a href="{% url 'booksmith:book_listing_form' %}" class="btn btn-secondary">List a book</a>
<br><br>
{% if books %}
<div class="row">
    {% for book in books %}
    <div class="col-md-2 mb-5">
        <div class="card">
            <div class="image-container">
                <img src="{{ book.cover_image.url }}" class="card-img-top fit-image" alt="{{ book.title }}">
            </div>
            <div class="card-body">
                <a href="{% url 'booksmith:book_detail' pk=book.id %}" class="btn btn-primary btn-secondary">Read
                    More</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<h3>No books available at the moment</h3>
{% endif %}
</div>
{% endblock %}