accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("verify-email/<str:token>/", views.verify_email_view, name="verify_email"),
]

booksmith/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "booksmith"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("book-listing-form/", views.BookListingFormView.as_view(), name="book_listing_form"),
    path("book-detail/<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("booksmith.urls")),
    path("accounts/", include("accounts.urls")),

    path("password-change/", auth_views.PasswordChangeView.as_view(), name="password_change"),
    path("password-change/done/", auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path("password-reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("verify-email/<str:uidb64>/<str:token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}
        <title>BookSmith</title>
        {% endblock %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>

    <body>
        {% include "header.html" %}
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        {% include "footer.html" %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    </body>

</html>

templates/footer.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}
        <title>BookSmith</title>
        {% endblock %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>

    <body>

        <footer class="text-center fixed-bottom mt-5 pt-3 pb-3 bg-dark text-white">&copy; 2023 BookSmith</footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>

    </body>

</html>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}
        <title> BookSmith</title>
        {% endblock %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>

    <body>

        <link rel="stylesheet" href="{% static 'css/header.css' %}">

        <nav class="navbar navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'booksmith:home' %}"><img src="{% static 'images/booksmith.png' %}"
                        alt="booksmith" style="width: 33px;"> BookSmith</a>

                <div id="primary-search-bar">
                    <form class="d-flex" role="search">
                        {% if request.path == "/" %}
                        <input class="form-control me-2 disabled" type="search" name="search" placeholder="Search"
                            aria-label="Search">
                        {% else %}
                        <input class="form-control me-2 disabled" type="search" name="search" placeholder="Search"
                            aria-label="Search" disabled>
                        {% endif %}
                        <button class="btn btn-success" type="submit"> Search</button>
                    </form>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
                    aria-labelledby="offcanvasDarkNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel"> BookSmith</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                            aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'booksmith:home' %}">
                                    Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"> Link</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    Account
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    {% if user.is_authenticated %}
                                    <li><a class="dropdown-item disabled" href="#"> {{ user.username }}</a></li>
                                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}"> Logout</a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'password_change' %}"> Change password</a>
                                    </li>
                                    {% else %}
                                    <li><a class="dropdown-item" href="{% url 'accounts:register' %}"> Register</a></li>
                                    <li><a class="dropdown-item" href="{% url 'accounts:login' %}"> Login</a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'password_reset' %}"> Reset password</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </li>
                        </ul>
                        <div id="secondary-search-bar">
                            <form class="d-flex mt-3" role="search">
                                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-success" type="submit"> Search</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </nav>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>

    </body>

</html>